//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use super::sea_orm_active_enums::FileStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::entities::{file_rule_match};
use crate::entities::prelude::FileRuleMatch;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub sha1sum: String,
    pub first_seen: DateTime,
    pub last_seen: DateTime,
    pub last_updated: DateTime,
    pub file_status: FileStatus,
    #[sea_orm(ignore)]
    pub signatures: Vec<String>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_rule_match::Entity")]
    FileRuleMatch,
}

impl Related<super::file_rule_match::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileRuleMatch.def()
    }
}

impl Model {
    pub async fn gen_signatures(&mut self, db: &DatabaseConnection) {
        self.signatures = FileRuleMatch::find()
            .filter(file_rule_match::Column::FileId.eq(self.id))
            .all(db)
            .await
            .unwrap_or_default()
            .into_iter()
            .map(|f| f.rule_name)
            .collect();
    }
}

impl ActiveModelBehavior for ActiveModel {}
