//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use clap::{Parser, ValueEnum};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Parser,
    ValueEnum,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_status")]
pub enum FileStatus {
    #[sea_orm(string_value = "good")]
    Good,
    #[sea_orm(string_value = "bad")]
    Bad,
    #[sea_orm(string_value = "whitelisted")]
    Whitelisted,
    #[sea_orm(string_value = "blacklisted")]
    Blacklisted,
}
