[package]
name = "dirk_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
base64 = "0.20"
clap = { version = "4.0", features = ["derive"] }
itertools = "0.10"
lazy_static = "1"
phpxdebug-parser = { git = "https://github.com/fzylogic/phpxdebug-parser-rs.git", branch = "main" }
regex = "1"
sea-orm = { version = "0.10", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sha256 = "1.1"
uuid = { version = "1.2", features = ["serde", "v4"] }