[package]
name = "dirk-api"
autobins = true
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
base64 = "0.20"
clap = { version = "4.0", features = ["derive"] }
dirk_core = { path = "../dirk_core" }
hyper = "0.14.23"
indicatif = "0.17"
itertools = "0.10"
lazy_static = "1.4.0"
phpxdebug-parser = { git = "https://github.com/fzylogic/phpxdebug-parser-rs.git", branch = "main" }
sea-orm = { version = "0.10", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sha256 = "1.1"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.22.0", features = ["macros", "net", "rt-multi-thread", "time"] }
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.3.0", features = ["add-extension", "trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.2", features = ["serde", "v4"] }
walkdir = "2"
tracing = "0.1"

[features]
mock = ["sea-orm/mock"]

[[test]]
name = "api"
required-features = ["mock"]
